### ISSUE TITLE
Doesn't compile on Ubuntu 24.04

### ISSUE THREAD

**Issue by Torgen** [jocosocial/swiftarr#323]
You're pinned to a released version of ZIPFoundation, but their last release didn't unwrap an optional value in the else case of a `#if os(macos) || ...` check. They fixed it at head in weichsel/ZIPFoundation#323, but they haven't released a version with the fix.

**Comment by hendricksond** [comment]
Which version of Swift are you using?

**Comment by Torgen** [comment]
```shell
$ swift --version
Swift version 5.10 (swift-5.10-RELEASE)
Target: x86_64-unknown-linux-gnu
```

**Comment by hendricksond** [comment]
Can you give an example of the error? 5.10 is the correct version for this project, and it's building fine for me on debian 12, even after cleaning the project. There are a lot of warnings, but I'm not seeing any build errors, and the server runs fine.

**Comment by Torgen** [comment]
```
/mnt/c/Users/Dan/Documents/GitHub/swiftarr/.build/checkouts/ZIPFoundation/Sources/ZIPFoundation/Archive+MemoryFile.swift:45:20: error: value of optional type 'UnsafeMutablePointer<FILE>?' (aka 'Optional<UnsafeMutablePointer<_IO_FILE>>') must be unwrapped to a value of type 'UnsafeMutablePointer<FILE>' (aka 'UnsafeMutablePointer<_IO_FILE>')
            fseeko(result, 0, SEEK_END)
                   ^
/mnt/c/Users/Dan/Documents/GitHub/swiftarr/.build/checkouts/ZIPFoundation/Sources/ZIPFoundation/Archive+MemoryFile.swift:45:20: note: coalesce using '??' to provide a default when the optional value contains 'nil'
            fseeko(result, 0, SEEK_END)
                   ^
                          ?? <#default value#>
/mnt/c/Users/Dan/Documents/GitHub/swiftarr/.build/checkouts/ZIPFoundation/Sources/ZIPFoundation/Archive+MemoryFile.swift:45:20: note: force-unwrap using '!' to abort execution if the optional value contains 'nil'
            fseeko(result, 0, SEEK_END)
                   ^
                         !
```

**Comment by Torgen** [comment]
It's possible it only affects Ubuntu 24.04, since that's also the version mentioned in weichsel/ZIPFoundation#320.

**Comment by hendricksond** [comment]
Not sure if there's anything we can really do to solve this until ZIPFoundation puts out a new version.

**Comment by challfry** [comment]
For now, you can locally switch the package() method to `package(url:revision:)`, so: `.package(url: "https://github.com/weichsel/ZIPFoundation.git", revision: "fac78dfe5a886ad98e355ba98475b30b3753213a")`. Assuming the fix is merged into head, that ought to get you up and compiling. I'd prefer to avoid merging in that sort of change to the package file (because no updates); here's hoping a new ZipFoundation release is forthcoming.

**Comment by Torgen** [comment]
As you may have been able to tell from the paths, my Ubuntu was on WSL, so I installed Debian as well and it seems to be working there.

**Comment by cohoe** [comment]
I haven't dug into this at all yet. We've used Ubuntu 22.04 as the server OS and base container image for the last two sailings in 2023 and 2024 (20.04 before that in 2022, the debut of Swiftarr). When I did my developing on Fedora 37ish there was a glibc update that made certain Swift features not work natively on my laptop. It took a release or two of the OS or Swift or both for that to sort itself out. Meaning this happens, and it's unfortunate. Yay evolving tech.

I do not intend on spending cycles to upgrade us to Ubuntu 24.04 for the 2025 sailing unless there is a really compelling reason to do so. The next big jump in my mind will likely come along with Swift 6.

**Comment by cohoe** [comment]
Can confirm on Ubuntu 24.04 (same error as Dan):

```
/swiftarr/.build/checkouts/ZIPFoundation/Sources/ZIPFoundation/Archive+MemoryFile.swift:45:20: error: value of optional type 'UnsafeMutablePointer<FILE>?' (aka 'Optional<UnsafeMutablePointer<_IO_FILE>>') must be unwrapped to a value of type 'UnsafeMutablePointer<FILE>' (aka 'UnsafeMutablePointer<_IO_FILE>')
 43 |         #endif
 44 |         if append {
 45 |             fseeko(result, 0, SEEK_END)
    |                    |- error: value of optional type 'UnsafeMutablePointer<FILE>?' (aka 'Optional<UnsafeMutablePointer<_IO_FILE>>') must be unwrapped to a value of type 'UnsafeMutablePointer<FILE>' (aka 'UnsafeMutablePointer<_IO_FILE>')
    |                    |- note: coalesce using '??' to provide a default when the optional value contains 'nil'
    |                    `- note: force-unwrap using '!' to abort execution if the optional value contains 'nil'
 46 |         }
 47 |         return result
/swiftarr/.build/checkouts/ZIPFoundation/Sources/ZIPFoundation/Archive+MemoryFile.swift:45:20: error: value of optional type 'UnsafeMutablePointer<FILE>?' (aka 'Optional<UnsafeMutablePointer<_IO_FILE>>') must be unwrapped to a value of type 'UnsafeMutablePointer<FILE>' (aka 'UnsafeMutablePointer<_IO_FILE>')
 43 |         #endif
 44 |         if append {
 45 |             fseeko(result, 0, SEEK_END)
    |                    |- error: value of optional type 'UnsafeMutablePointer<FILE>?' (aka 'Optional<UnsafeMutablePointer<_IO_FILE>>') must be unwrapped to a value of type 'UnsafeMutablePointer<FILE>' (aka 'UnsafeMutablePointer<_IO_FILE>')
    |                    |- note: coalesce using '??' to provide a default when the optional value contains 'nil'
    |                    `- note: force-unwrap using '!' to abort execution if the optional value contains 'nil'
 46 |         }
 47 |         return result
/swiftarr/.build/checkouts/ZIPFoundation/Sources/ZIPFoundation/Archive+MemoryFile.swift:45:20: error: value of optional type 'UnsafeMutablePointer<FILE>?' (aka 'Optional<UnsafeMutablePointer<_IO_FILE>>') must be unwrapped to a value of type 'UnsafeMutablePointer<FILE>' (aka 'UnsafeMutablePointer<_IO_FILE>')
 43 |         #endif
 44 |         if append {
 45 |             fseeko(result, 0, SEEK_END)
    |                    |- error: value of optional type 'UnsafeMutablePointer<FILE>?' (aka 'Optional<UnsafeMutablePointer<_IO_FILE>>') must be unwrapped to a value of type 'UnsafeMutablePointer<FILE>' (aka 'UnsafeMutablePointer<_IO_FILE>')
    |                    |- note: coalesce using '??' to provide a default when the optional value contains 'nil'
    |                    `- note: force-unwrap using '!' to abort execution if the optional value contains 'nil'
 46 |         }
 47 |         return result
[230/1242] Compiling Logging MetadataProvider.swift
```

And that replacing the line in `Package.swift` with `.package(url: "https://github.com/weichsel/ZIPFoundation.git", revision: "fac78dfe5a886ad98e355ba98475b30b3753213a")` as Chall described makes it compile.

**Comment by cohoe** [comment]
Interesting note related to Swift 6 (#333): I had to use `swift [run|build] --use-integrated-swift-driver` to avoid random compiler failures:
```
error: failed parsing the Swift compiler output: unexpected JSON message: {
 "command_arguments" : [
    "-frontend",
    "-c",
...
...
    "\/swiftarr\/.build\/checkouts\/swift-nio\/Sources\/NIOCore\/AsyncSequences\/NIOAsyncSequenceProducerStrategies.swift",
    "\/swiftarr\/.build\/checkouts\/swift-nio\/Sources\/NIOCore\/AsyncSe: dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: nil))
```

https://forums.swift.org/t/compiler-crashing-with-unhelpful-error/62138
https://forums.swift.org/t/project-does-not-compile-with-swift-6-on-windows-but-on-macos/75435
